FilOzone/filecoin-services

service_contracts/src/SimplePDPServiceWithPayments.sol, service_contracts/test/SignatureFixtureTest.t.sol, service_contracts/test/external_signatures.json
We have an easier time in JavaScript emulating this.
Also:
vs
=> fix(auth): ScheduleRemovals should use uint256[]

service_contracts/src/PandoraService.sol, service_contracts/test/PandoraService.t.sol, service_contracts/tools/README.md, service_contracts/tools/deploy-all-pandora-calibnet.sh, service_contracts/tools/deploy-pandora-calibnet.sh, service_contracts/tools/upgrade-pandora-calibnet.sh
- change them into constants that are configured upon contract deployment
- updated the deploy scripts to set them
- updated the default value for testnets 30epochs and 15 epochs accordingly to allow faster testing iteration
=> feat: update proving window and max challenge window size

subgraph/src/decode.ts, subgraph/src/pandora-service.ts
Changes - 
- Detects the emitting function by inspecting transaction input data.
- If the event was emitted by addServiceProvider, decodes pdpUrl and pieceRetrievalUrl and stores them in the corresponding Provider entity.
- Retains existing logic for approveServiceProvider.
fixes #56
=> fix: distinguish between `approveServiceProvider` & `addServiceProvider` in ProviderApproved handler

service_contracts/src/PandoraService.sol, service_contracts/test/PandoraService.t.sol
Updates the service creator fee configuration to set the basic service commission to 0% as requested in #59.
=> chore: set basic service commission to 0% (was 5%)

service_contracts/Makefile, service_contracts/foundry.toml, service_contracts/src/PandoraService.sol, service_contracts/test/PandoraService.t.sol
This PR introduces robust support for proof set ownership changes in the `PandoraService` contract, as well as tests validating this new behavior. This feature enables secure key rotation and improves the protocol's flexibility for storage providers, while maintaining registry and payment rail consistency. This work addresses issue [#15 ]
---
* **New Event:**
* `ProofSetOwnershipChanged(uint256 indexed proofSetId, address indexed oldOwner, address indexed newOwner)` is emitted whenever proof set ownership is transferred, improving transparency for off-chain tracking.
* **Updated Logic in `ownerChanged`:**
* Validates proof set existence and correct old owner.
* Ensures new owner is not zero address and not already a registered provider (avoiding registry corruption).
* Updates the …
=> Add Proof Set Ownership Change Logic to PandoraService

.github/workflows/add-issues-and-prs-to-fs-project-board.yml
Part of https://github.com/FilOzone/github-mgmt/issues/10.  It didn't originally get created with github-mgmt because of the branch protection rule.
=> ci: create add-issues-and-prs-to-fs-project-board.yml

service_contracts/tools/check-contract-size.sh
Reviewer @rvagg
CC @pali101
Consider the behavior of the contract size tool when the build fails.
previous output:
```
All contracts are within the EIP-170 runtime and EIP-3860 init code size limits.
```
new output:
```
forge did not find any contracts. forge build:
[⠊] Compiling...
[⠰] Compiling 79 files with Solc 0.8.27
[⠔] Solc 0.8.27 finished in 360.09ms
Error: Compiler run failed:
Error (2314): Expected identifier but got 'uint8'
--> test/FilecoinWarmStorageService.t.sol:19:11:
|
19 |     uint8 uint8 private _decimals = 6;
|           ^^^^^
```
* check for empty output dictionary
=> Check Contract Size: Handle Forge Build Error

.gitmodules, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
- Changed 4 functions from public to external: initChallengeWindowStart(), nextChallengeWindowStart(), getClientDataSets(), getDataSetSizeInBytes()
- Consolidated 3 rate calculation functions into 1 external + 2 internal functions for efficient conditional usage
- Removed 7 redundant functions:
- isProviderApproved() → use getProviderIdByAddress(provider) != 0
- 6 DataSet getters (getDataSetPdpRailId, getDataSetCacheMissRailId, getDataSetCDNRailId, getDataSetParties, getDataSetMetadata, getDataSetWithCDN) → use getDataSet(id).fieldName
Contract size savings: ~650 bytes
=> feat!: optimize contract size

service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
$2 quintillion per TiB for storage anyone? (2,000,000,000,000,000,000 USD per TiB/month)
#66 introduced the multiplication in the constructor, they were previously un-multiplied constants, so now we have double multiplication.
=> fix: no double-multiplication of pricing values

service_contracts/tools/deploy-all-warm-storage-calibnet.sh, service_contracts/tools/deploy-warm-storage-calibnet.sh, service_contracts/tools/deploy-warm-storage-implementation-only.sh
Some simple updates to match current constructor and other changes in the contracts. Thankfully too many constructor arguments isn't a fatal thing in `forge create`, it'll just ignore them, so this goes unnoticed mainly.
=> fix: make deploy scripts match current contracts

service_contracts/src/Errors.sol, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
This PR does the first part of #119 i.e. removes all the code and tests for the service provider registry from this service contract. We will now build a new more extensible service registry contract  as specified in #119 and upgrade the warm storage service contract to use the registry. More PRs incoming for that.
But we can merge this standalone PR without waiting on them.
=> feat: remove service provider registry as we're moving it to it's own contract

service_contracts/src/FilecoinWarmStorageService.sol
Reviewer @ZenGround0
This matches the licensing in `src/Errors.sol` and also the policy [here](https://www.protocol.ai/blog/announcing-the-permissive-license-stack/)
I did not update the license header for the tests. I can do that upon request.
* license
=> FWSS: License

service_contracts/tools/deploy-all-warm-storage-calibnet.sh, service_contracts/tools/deploy-warm-storage-view.sh
matching the other deploy contracts, keystore's don't have to be password locked
=> fix: make deploy-warm-storage-view.sh work

service_contracts/src/FilecoinWarmStorageServiceStateView.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateInternalLibrary.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateLibrary.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
To differentiate between exists but empty, and doesn't exist. i.e. without this, you can't distinguish between the two cases, if it doesn't exist, you'll get `""` anyway.
I thought I had this on the metadata PR already, I think it might have got lost in the huge rebase I did! I noticed in https://github.com/FilOzone/filecoin-services/pull/142 that it has the same problem, I went to look for a reference to link to and discovered it wasn't there on main, so whoops!
=> feat(metadata): get(key) returns (exists, value)

service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
price is updated based on the product research done by @timfong888 and @patrickwoodhead 
note that we expect the pricing schema to be changing in beta 
this is a breaking change as the STORAGE_PRICE_PER_TIB_PER_MONTH is immutable
=> feat!: update storage price for alpha on mainnet

service_contracts/Makefile
Reviewer @rvagg
There are a few problems with the `FilecoinWarmStorageServiceStateLibrary.json` recipe.
It hides important information about why the build failed.
It behaves as if the recipe succeeded even when it failed.
* do not hide the build errors
* do not proceed as if successful when the build fails
* no need to --force the build
=> Fix StateLibrary json Makefile recipe

service_contracts/Makefile, service_contracts/src/FilecoinWarmStorageServiceStateView.sol, service_contracts/src/lib/FilecoinWarmStorageServiceLayout.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateInternalLibrary.sol, service_contracts/tools/generate_storage_layout.sh, service_contracts/tools/generate_view_contract.sh
different shells, different OS' causing inconsistency in the comment at the top of the generated files, so this is simplifying it and not using the input to determine the output
=> fix(ci): consistent comments for codegen

service_contracts/abi/FilecoinWarmStorageService.abi.json, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/src/lib/FilecoinWarmStorageServiceLayout.sol
Same as https://github.com/FilOzone/filecoin-services/pull/196, which was accidentally re-applied due to miscommunication.
=> fix: remove serviceName and serviceDescription properties

service_contracts/tools/deploy-all-warm-storage-calibnet.sh, service_contracts/tools/deploy-session-key-registry.sh, service_contracts/tools/deploy-warm-storage-view.sh, service_contracts/tools/set-warm-storage-view.sh
Couple of minor cleanups having run through this. The main annoyance was `setViewContract` coming out with very verbose output, now it's nice and compact and I extracted it to a separate script in the pattern that's developing in there.
=> fix(deploy): handle setViewContract more gracefully; auto-detect chainId

service_contracts/Makefile, service_contracts/abi/PDPVerifier.abi.json, service_contracts/abi/Payments.abi.json
Reviewer @hugomrdias
Also checkin these ABIs
Now all of the abis used by synapse-sdk are in the same repo.
By pinning them in this repo we can use one tag to mark an abi release, used by synapse-sdk and curio.
* add Payments and PDPVerifier to list of abis
* make update-abi
=> Payments And Pdp Abi

service_contracts/CONTRIBUTING.md, service_contracts/Makefile, service_contracts/README.md
Reviewer @rvagg
The on-failure restoration was putting the files into the wrong directory.
I agree that we should just remove safe-gen.
We can use version control or other approaches to backup if necessary.
* rm `safe-gen`
=> rm safe-gen

service_contracts/tools/deploy-all-warm-storage-calibnet.sh
Getting nonce errors otherwise, I think maybe the delay isn't enough between the two steps so `cast nonce` isn't picking up the used nonce for the session key registry.
=> fix: handle nonce properly in deploy script

service_contracts/abi/ServiceProviderRegistry.abi.json, service_contracts/src/ServiceProviderRegistry.sol, service_contracts/src/ServiceProviderRegistryStorage.sol, service_contracts/test/ServiceProviderRegistry.t.sol, service_contracts/test/ServiceProviderRegistryFull.t.sol
Add providerId to ServiceInfo for easy provider lookup.
=> feat: service registry: add providerId to ServiceInfo

service_contracts/.gitignore, service_contracts/abi/FilecoinWarmStorageServiceStateLibrary.abi.json, service_contracts/abi/FilecoinWarmStorageServiceStateView.abi.json, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/src/FilecoinWarmStorageServiceStateView.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateInternalLibrary.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateLibrary.sol, service_contracts/test/FilecoinWarmStorageService.t.sol, service_contracts/test/FilecoinWarmStorageServiceOwner.t.sol
Fixes https://github.com/FilOzone/filecoin-services/issues/235
This PR adds a new struct DataSetInfoView and returns the same for getClientDataSets. The new struct is a copy of DataSetInfo with additional parameter `uint256 dataSetId`.
=> feat: update getClientDataSets to return dataSetId

service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol, service_contracts/test/FilecoinWarmStorageServiceOwner.t.sol
This is a breaking change as the fields updated is immutable/constants.  
- change locking period to 30 days
- change per copy price to USDFC2.5 ($5 for 2 copies)
=> feat!: update service parameters 

service_contracts/abi/ServiceProviderRegistry.abi.json, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/src/ServiceProviderRegistry.sol, service_contracts/src/ServiceProviderRegistryStorage.sol, service_contracts/test/ServiceProviderRegistry.t.sol, service_contracts/test/ServiceProviderRegistryFull.t.sol
Remove `providerId` from `ServiceProviderInfo` struct and introduce `ServiceProviderInfoView` as a view struct to return provider ID with provider info.
Fixes #234
- **Removed** `providerId` field from `ServiceProviderInfo` struct
- **Added** `ServiceProviderInfoView` struct with `providerId` field for external consumption
- **Updated** all getter functions to return `ServiceProviderInfoView`
- **Updated** tests and ABI definitions
- `ServiceProviderRegistry.sol`
- `ServiceProviderRegistryStorage.sol` 
- `FilecoinWarmStorageService.sol`
- Test files and ABI
=> feat: remove provierId from ServiceProviderInfo struct

service_contracts/abi/ServiceProviderRegistry.abi.json, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/src/ServiceProviderRegistry.sol, service_contracts/test/ServiceProviderRegistry.t.sol
Implements a helper function to fetch only the payee address for service providers, reducing the access footprint of `CreateDataSet`.
Currently, `FilecoinWarmStorageService.dataSetCreated()` calls `getProvider(providerId)` which reads the entire `ServiceProviderInfo` struct from storage, including expensive string fields (`name` and `description`), when only the `payee` address is needed.
- **Added `getProviderPayee(uint256 providerId)`** in `ServiceProviderRegistry.sol`
- Returns only the payee address directly from storage
- Uses `providerExists` modifier for safety
- **Updated `FilecoinWarmStorageService.sol`**
- Replaced `getProvider()` call with `getProviderPayee()` in `dataSetCreated()`
- Eliminates intermediate struct creation and string reads
- **Added unit tests**
- …
=> perf(ServiceProviderRegistry): getProviderPayee helper for dataSetCreated

README.md, service_contracts/tools/README.md, service_contracts/tools/deploy-all-warm-storage.sh
Closes: #221 
Consolidate deployment docs to eliminate duplication, and document the different deployment parameters for Calibration and Mainnet.
=> docs: consolidate deployment docs to eliminate duplication 

service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/test/FilecoinWarmStorageService.t.sol, service_contracts/test/FilecoinWarmStorageServiceOwner.t.sol
Towards #254
We are cutting a set of contracts for the M3 milestone. The price changes in #239 was done with https://github.com/FilOzone/filecoin-services/issues/250 being landed in mind. 
Since #250 is not going to land before in M4, I have temporarily reverted the price changes, so that we keep the price intact for the M3 contract publishing.
=> chore: temporarily revert of price changes in #239

service_contracts/foundry.toml, service_contracts/src/FilecoinWarmStorageService.sol, service_contracts/src/lib/FilecoinWarmStorageServiceLayout.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateInternalLibrary.sol, service_contracts/src/lib/FilecoinWarmStorageServiceStateLibrary.sol, service_contracts/test/FilecoinWarmStorageService.t.sol
Reviewer @rvagg @kubuxu
Closes https://github.com/FilOzone/filecoin-services/issues/257
This should reduce the proof storage growth by a factor of 256.
If the proving period is 1 day, and the deal lasts 1 year, this mapping will use 2 slots instead of 356.
* Change provenPeriods to bitmap
=> perf(provenPeriods): bitmap

CHANGELOG.md
Towards: https://github.com/FilOzone/filecoin-services/issues/254
Although currently blocked on pushing releases until https://github.com/FilOzone/pdp/issues/210 is out, a initial review of the changelog at this point seems like a good starting point
=> chore: prep v0.2.0 changelog
